[patch]
title = "BingusEXE6"
authors = [
    "ssbmars <46971717+ssbmars@users.noreply.github.com>",
]
source = "https://github.com/ssbmars/BBN6"
license = "MIT"
for_rom = "ROCKEXE6_GXXBR5J"

[versions.'0.0.1']
netplay_compatibility = "bingusexe6"
[versions.'1.0.0']
netplay_compatibility = "bingusexe6"
