[patch]
title = "BingusEXE6 F"
authors = [
    "ssbmars <46971717+ssbmars@users.noreply.github.com>",
]
source = "https://github.com/ssbmars/BBN6"
license = "MIT"
for_rom = "ROCKEXE6_RXXBR6J"

[versions.'1.0.0']
netplay_compatibility = "bingusexe6v1"
