[patch]
title = "BingusBN6+SoundMod"
authors = [
	"ssbmars <46971717+ssbmars@users.noreply.github.com>",
	"オレ{Ore} <oreo7863@gmail.com>",
]
source = "https://github.com/ssbmars/BBN6"
license = "MIT"

